if has("autocmd")
        autocmd! bufwritepost .vimrc source ~/.vimrc
endif

set nocp
source ~/dotfile/vim/autoload/pathogen.vim
call pathogen#infect('~/dotfile/vim/bundle/{}')
call pathogen#helptags()

let g:vimwiki_list = [
                        \{'path': '~/dotfile/vim/vimwiki/personal.md'}
                    \]
filetype on
filetype plugin on
syntax on
set t_Co=256
source ~/dotfile/vim/colors/mrkn256.vim
set number
set hidden
set history=500
filetype indent on
set nowrap
set expandtab
set smartindent
set autoindent
autocmd BufWritePre * :%s/\s\+$//e
set hlsearch
set laststatus=2
set noshowmode
let mapleader=' '
map <leader>n :NERDTreeToggle<CR>
